import { relations } from 'drizzle-orm';
import { integer, pgTable, serial, text, timestamp, doublePrecision } from 'drizzle-orm/pg-core';

// 1. Users table (linked to Firebase Auth UID)
export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  uid: text('uid').notNull().unique(), // Firebase Auth UID
  email: text('email').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
});

// 2. Products table (inventory items)
export const products = pgTable('products', {
  id: serial('id').primaryKey(),
  userId: integer('user_id')
    .references(() => users.id)
    .notNull(),
  sku: text('sku').notNull(),
  name: text('name').notNull(),
  category: text('category').notNull(),
  stockLevel: integer('stock_level').notNull().default(0),
  reorderPoint: integer('reorder_point').notNull().default(10),
  unitPrice: doublePrecision('unit_price').notNull().default(0.0),
  leadTimeDays: integer('lead_time_days').notNull().default(7),
  createdAt: timestamp('created_at').defaultNow(),
});

// 3. Sales History table (historical actual demand data)
export const salesHistory = pgTable('sales_history', {
  id: serial('id').primaryKey(),
  productId: integer('product_id')
    .references(() => products.id, { onDelete: 'cascade' })
    .notNull(),
  saleDate: text('sale_date').notNull(), // format: YYYY-MM-DD
  quantitySold: integer('quantity_sold').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
});

// 4. Forecasts table (cached forecasts generated by the models)
export const forecasts = pgTable('forecasts', {
  id: serial('id').primaryKey(),
  productId: integer('product_id')
    .references(() => products.id, { onDelete: 'cascade' })
    .notNull(),
  forecastDate: text('forecast_date').notNull(), // format: YYYY-MM-DD
  forecastQuantity: doublePrecision('forecast_quantity').notNull(),
  modelType: text('model_type').notNull(), // 'Holt-Winters', 'SMA', 'ARIMA-fit', 'Gemini-AI'
  createdAt: timestamp('created_at').defaultNow(),
});

// Relations
export const usersRelations = relations(users, ({ many }) => ({
  products: many(products),
}));

export const productsRelations = relations(products, ({ one, many }) => ({
  user: one(users, {
    fields: [products.userId],
    references: [users.id],
  }),
  salesHistory: many(salesHistory),
  forecasts: many(forecasts),
}));

export const salesHistoryRelations = relations(salesHistory, ({ one }) => ({
  product: one(products, {
    fields: [salesHistory.productId],
    references: [products.id],
  }),
}));

export const forecastsRelations = relations(forecasts, ({ one }) => ({
  product: one(products, {
    fields: [forecasts.productId],
    references: [products.id],
  }),
}));
